import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig } from '../../../../schemas';

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

export const generateComplianceReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFillColor(0, 31, 63);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Compliance Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(config.title, 105, 30, { align: 'center' });

  doc.setTextColor(0, 0, 0);
  yPos = 50;

  // Report metadata
  doc.setFontSize(9);
  doc.text(`Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`, 20, yPos);
  yPos += 5;
  doc.text(`Generated By: ${config.generatedBy}`, 20, yPos);
  yPos += 10;

  // Standards reference from backend
  if (reportData.standards) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Regulatory Standards', 20, yPos);
    yPos += 7;

    const standards = reportData.standards;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Turbidity: ${standards.turbidity || 'N/A'}`, 20, yPos);
    yPos += 4;
    doc.text(`TDS: ${standards.tds || 'N/A'}`, 20, yPos);
    yPos += 4;
    doc.text(`pH: ${standards.ph || 'N/A'}`, 20, yPos);
    yPos += 4;
    doc.text(`Reference: ${standards.reference || 'WHO/EPA Standards'}`, 20, yPos);
    yPos += 10;
  }

  // Compliance summary from backend
  if (reportData.summary) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Compliance Summary', 20, yPos);
    yPos += 7;

    const summary = reportData.summary;
    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['Total Devices', summary.totalDevices?.toString() || 'N/A'],
        ['Compliant Devices', summary.compliantDevices?.toString() || 'N/A'],
        ['Compliance Rate', summary.complianceRate || 'N/A'],
      ],
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [0, 31, 63] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
  }

  // Device compliance details from backend
  if (reportData.devices && reportData.devices.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Device Compliance Details', 20, yPos);
    yPos += 7;

    for (const deviceCompliance of reportData.devices) {
      if (yPos > 240) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(`Device: ${deviceCompliance.deviceName || deviceCompliance.deviceId}`, 20, yPos);
      yPos += 5;

      if (deviceCompliance.complianceStatus) {
        const complianceData = deviceCompliance.complianceStatus.map((status: any) => [
          status.parameter || 'N/A',
          status.value?.toFixed(2) || 'N/A',
          status.standard?.toString() || 'N/A',
          status.status?.toUpperCase() || 'UNKNOWN',
          `${status.percentage?.toFixed(1) || '0'}%`
        ]);

        autoTable(doc, {
          startY: yPos,
          head: [['Parameter', 'Value', 'Standard', 'Status', 'Compliance %']],
          body: complianceData,
          styles: { fontSize: 7, cellPadding: 2 },
          headStyles: { fillColor: [0, 31, 63] },
          alternateRowStyles: { fillColor: [245, 245, 245] },
          columnStyles: {
            3: { fontStyle: 'bold' }
          },
          didParseCell: function(data: any) {
            if (data.column.index === 3) {
              const status = data.cell.raw.toLowerCase();
              if (status === 'compliant') {
                data.cell.styles.textColor = [82, 196, 26];
              } else {
                data.cell.styles.textColor = [255, 77, 79];
              }
            }
          },
        });

        yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 8;
      }
    }
  }

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text(
      `IoT Compliance Monitoring System - ${dayjs().format('YYYY')}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
};
