import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig, SensorReading } from '../../../../schemas';
import { calculateStatistics, calculateDataCompleteness } from '../utils';

// ============================================================================
// CONSTANTS - Design System
// ============================================================================
const COLORS = {
  primary: { r: 0, g: 31, b: 63 },
  secondary: { r: 41, g: 128, b: 185 },
  success: { r: 82, g: 196, b: 26 },
  warning: { r: 250, g: 173, b: 20 },
  danger: { r: 255, g: 77, b: 79 },
  gray: { r: 128, g: 128, b: 128 },
  lightGray: { r: 245, g: 245, b: 245 },
  white: { r: 255, g: 255, b: 255 },
  text: { r: 51, g: 51, b: 51 },
};

const SPACING = {
  page: { top: 20, bottom: 25, left: 15, right: 15 },
  section: 12,
};

const FONTS = {
  title: { size: 24, style: 'bold' },
  subtitle: { size: 14, style: 'normal' },
  heading: { size: 12, style: 'bold' },
  subheading: { size: 10, style: 'bold' },
  body: { size: 9, style: 'normal' },
  small: { size: 8, style: 'normal' },
  tiny: { size: 7, style: 'normal' },
};

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

export const generateDataSummaryReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  const reportId = `DSR-${dayjs().format('YYYYMMDD')}-${Math.random().toString(36).substr(2, 6).toUpperCase()}`;
  let yPos = 0;

  // ============================================================================
  // HEADER
  // ============================================================================
  doc.setFillColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  doc.rect(0, 0, 210, 50, 'F');
  
  doc.setTextColor(COLORS.white.r, COLORS.white.g, COLORS.white.b);
  doc.setFont('helvetica', FONTS.title.style);
  doc.setFontSize(FONTS.title.size);
  doc.text('Data Summary Report', 105, 22, { align: 'center' });
  
  doc.setFont('helvetica', FONTS.subtitle.style);
  doc.setFontSize(FONTS.subtitle.size);
  doc.text(config.title, 105, 32, { align: 'center' });
  
  doc.setFont('helvetica', FONTS.small.style);
  doc.setFontSize(FONTS.small.size);
  doc.text(`Report ID: ${reportId}`, 105, 42, { align: 'center' });

  doc.setFillColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
  doc.rect(0, 50, 210, 2, 'F');

  yPos = 60;

  // ============================================================================
  // REPORT INFORMATION
  // ============================================================================
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  
  doc.setFillColor(COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b);
  doc.roundedRect(SPACING.page.left, yPos, 180, 18, 2, 2, 'F');
  
  doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
  doc.setLineWidth(0.3);
  doc.roundedRect(SPACING.page.left, yPos, 180, 18, 2, 2, 'S');
  
  yPos += 7;
  
  doc.setFont('helvetica', FONTS.subheading.style);
  doc.setFontSize(FONTS.subheading.size);
  doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
  doc.text('Report Information', SPACING.page.left + 5, yPos);
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  yPos += 7;

  doc.setFont('helvetica', FONTS.body.style);
  doc.setFontSize(FONTS.body.size);
  
  doc.text(`Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`, SPACING.page.left + 5, yPos);
  doc.text(`Generated By: ${config.generatedBy}`, 110, yPos);
  
  yPos += 10;

  // Summary statistics from backend or calculated locally
  let summaryData = reportData.summary;
  
  // If no backend summary, calculate from local data
  if (!summaryData && reportData.devices && reportData.devices.length > 0) {
    const allReadings: SensorReading[] = [];
    reportData.devices.forEach((device: any) => {
      if (device.readings && Array.isArray(device.readings)) {
        allReadings.push(...device.readings);
      }
    });
    
    summaryData = {
      totalReadings: allReadings.length,
      totalDevices: reportData.devices.length,
      dataCompleteness: calculateDataCompleteness(
        allReadings.length,
        reportData.period?.start,
        reportData.period?.end
      ),
    };
  }
  
  // ============================================================================
  // DATA SUMMARY
  // ============================================================================
  if (summaryData) {
    doc.setFont('helvetica', FONTS.heading.style);
    doc.setFontSize(FONTS.heading.size);
    doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.text('Data Summary', SPACING.page.left, yPos);
    
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos + 2, SPACING.page.left + 35, yPos + 2);
    
    yPos += 10;

    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['📊 Total Readings', summaryData.totalReadings?.toString() || 'N/A'],
        ['📍 Total Devices', summaryData.totalDevices?.toString() || 'N/A'],
        ['✓ Data Completeness', summaryData.dataCompleteness || 'N/A'],
      ],
      styles: { 
        fontSize: FONTS.body.size, 
        cellPadding: 3,
        lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
        lineWidth: 0.1,
      },
      headStyles: { 
        fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
        textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
        fontStyle: 'bold',
      },
      alternateRowStyles: { 
        fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b] 
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 70 },
      },
      margin: { left: SPACING.page.left, right: SPACING.page.right },
    });

    yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
    yPos += 10;
  }

  // ============================================================================
  // STATISTICAL ANALYSIS
  // ============================================================================
  if (reportData.statistics) {
    if (yPos > 220) {
      doc.addPage();
      yPos = SPACING.page.top;
    }

    doc.setFont('helvetica', FONTS.heading.style);
    doc.setFontSize(FONTS.heading.size);
    doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);
    doc.text('Statistical Analysis', SPACING.page.left, yPos);
    
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos + 2, SPACING.page.left + 50, yPos + 2);
    
    yPos += 10;

    const stats = reportData.statistics;
    const statsData = [];

    if (stats.turbidity) {
      statsData.push(['💧 Turbidity', 'Mean', stats.turbidity.mean?.toFixed(2) || 'N/A', 'NTU']);
      statsData.push(['', 'Std Dev', stats.turbidity.stdDev?.toFixed(2) || 'N/A', 'NTU']);
      statsData.push(['', 'Min / Max', `${stats.turbidity.min?.toFixed(2) || 'N/A'} / ${stats.turbidity.max?.toFixed(2) || 'N/A'}`, 'NTU']);
    }

    if (stats.tds) {
      statsData.push(['⚗️ TDS', 'Mean', stats.tds.mean?.toFixed(2) || 'N/A', 'ppm']);
      statsData.push(['', 'Std Dev', stats.tds.stdDev?.toFixed(2) || 'N/A', 'ppm']);
      statsData.push(['', 'Min / Max', `${stats.tds.min?.toFixed(2) || 'N/A'} / ${stats.tds.max?.toFixed(2) || 'N/A'}`, 'ppm']);
    }

    if (stats.ph) {
      statsData.push(['🔬 pH', 'Mean', stats.ph.mean?.toFixed(2) || 'N/A', '']);
      statsData.push(['', 'Std Dev', stats.ph.stdDev?.toFixed(2) || 'N/A', '']);
      statsData.push(['', 'Min / Max', `${stats.ph.min?.toFixed(2) || 'N/A'} / ${stats.ph.max?.toFixed(2) || 'N/A'}`, '']);
    }

    if (statsData.length > 0) {
      autoTable(doc, {
        startY: yPos,
        head: [['Parameter', 'Statistic', 'Value', 'Unit']],
        body: statsData,
        styles: { 
          fontSize: FONTS.small.size, 
          cellPadding: 2.5,
          lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
          lineWidth: 0.1,
        },
        headStyles: { 
          fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
          textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
          fontSize: FONTS.body.size,
          fontStyle: 'bold',
        },
        alternateRowStyles: { 
          fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b] 
        },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 35 },
          1: { cellWidth: 25 },
        },
        margin: { left: SPACING.page.left, right: SPACING.page.right },
      });
      
      yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
    }
  } else if (reportData.devices && reportData.devices.length > 0) {
    // Fallback: Calculate statistics from device readings if no backend statistics available
    
    // Section header with decorative underline
    doc.setFontSize(FONTS.heading.size);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
    doc.text('📊 Statistical Analysis (Local Data)', SPACING.page.left, yPos);
    yPos += 2;
    doc.setDrawColor(COLORS.secondary.r, COLORS.secondary.g, COLORS.secondary.b);
    doc.setLineWidth(0.8);
    doc.line(SPACING.page.left, yPos, SPACING.page.left + 50, yPos);
    yPos += 8;
    
    // Collect all readings from all devices
    const allReadings: SensorReading[] = [];
    reportData.devices.forEach((device: any) => {
      if (device.readings && Array.isArray(device.readings)) {
        allReadings.push(...device.readings);
      }
    });
    
    if (allReadings.length > 0) {
      const turbidityData = allReadings.map((r: SensorReading) => r.turbidity);
      const tdsData = allReadings.map((r: SensorReading) => r.tds);
      const phData = allReadings.map((r: SensorReading) => r.ph);
      
      const turbidityStats = calculateStatistics(turbidityData);
      const tdsStats = calculateStatistics(tdsData);
      const phStats = calculateStatistics(phData);
      
      const fallbackStatsData = [
        ['💧 Turbidity', 'Mean', turbidityStats.mean.toFixed(2), 'NTU'],
        ['', 'Std Dev', turbidityStats.stdDev.toFixed(2), 'NTU'],
        ['', 'Min/Max', `${turbidityStats.min.toFixed(2)} / ${turbidityStats.max.toFixed(2)}`, 'NTU'],
        ['⚗️ TDS', 'Mean', tdsStats.mean.toFixed(2), 'ppm'],
        ['', 'Std Dev', tdsStats.stdDev.toFixed(2), 'ppm'],
        ['', 'Min/Max', `${tdsStats.min.toFixed(2)} / ${tdsStats.max.toFixed(2)}`, 'ppm'],
        ['🔬 pH', 'Mean', phStats.mean.toFixed(2), ''],
        ['', 'Std Dev', phStats.stdDev.toFixed(2), ''],
        ['', 'Min/Max', `${phStats.min.toFixed(2)} / ${phStats.max.toFixed(2)}`, ''],
      ];
      
      autoTable(doc, {
        startY: yPos,
        head: [['Parameter', 'Statistic', 'Value', 'Unit']],
        body: fallbackStatsData,
        styles: { 
          fontSize: FONTS.small.size,
          cellPadding: 2.5,
          lineColor: [COLORS.gray.r, COLORS.gray.g, COLORS.gray.b],
          lineWidth: 0.1,
        },
        headStyles: { 
          fillColor: [COLORS.primary.r, COLORS.primary.g, COLORS.primary.b],
          textColor: [COLORS.white.r, COLORS.white.g, COLORS.white.b],
          fontSize: FONTS.body.size,
          fontStyle: 'bold',
        },
        alternateRowStyles: { 
          fillColor: [COLORS.lightGray.r, COLORS.lightGray.g, COLORS.lightGray.b]
        },
        columnStyles: {
          0: { fontStyle: 'bold', cellWidth: 35 },
          1: { cellWidth: 25 },
        },
        margin: { left: SPACING.page.left, right: SPACING.page.right },
      });
      
      yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
    } else {
      doc.setFontSize(FONTS.body.size);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
      doc.text('No sensor data available for statistical analysis.', SPACING.page.left, yPos);
      yPos += 10;
    }
  }

  // Professional footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer separator line
    doc.setDrawColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
    doc.setLineWidth(0.5);
    doc.line(SPACING.page.left, 280, 195, 280);
    
    // Page numbers (centered)
    doc.setFontSize(FONTS.small.size);
    doc.setTextColor(COLORS.gray.r, COLORS.gray.g, COLORS.gray.b);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    
    // Copyright and Report ID (centered)
    doc.setFontSize(FONTS.tiny.size);
    doc.text(
      `© ${dayjs().format('YYYY')} PureTrack | Report ID: ${reportId}`,
      105,
      289,
      { align: 'center' }
    );
    
    // Generation timestamp (centered)
    doc.text(
      `Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`,
      105,
      293,
      { align: 'center' }
    );
  }

  return doc;
};
