import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig } from '../../../../schemas';

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

export const generateDeviceStatusReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF();
  let yPos = 20;

  // Header
  doc.setFillColor(0, 31, 63);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Device Status Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(config.title, 105, 30, { align: 'center' });

  doc.setTextColor(0, 0, 0);
  yPos = 50;

  // Report Info
  doc.setFontSize(9);
  doc.text(`Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`, 20, yPos);
  yPos += 5;
  doc.text(`Generated By: ${config.generatedBy}`, 20, yPos);
  yPos += 10;

  // Backend summary data
  if (reportData.summary) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('System Overview', 20, yPos);
    yPos += 7;

    const summary = reportData.summary;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Devices: ${summary.totalDevices}`, 20, yPos);
    yPos += 5;
    doc.text(`Health Score: ${summary.healthScore}%`, 20, yPos);
    yPos += 10;

    if (summary.statusBreakdown) {
      autoTable(doc, {
        startY: yPos,
        head: [['Status', 'Count', 'Percentage']],
        body: [
          ['Online', summary.statusBreakdown.online?.toString() || '0', `${summary.statusBreakdown.online || 0}%`],
          ['Offline', summary.statusBreakdown.offline?.toString() || '0', `${summary.statusBreakdown.offline || 0}%`],
          ['Error', summary.statusBreakdown.error?.toString() || '0', `${summary.statusBreakdown.error || 0}%`],
          ['Maintenance', summary.statusBreakdown.maintenance?.toString() || '0', `${summary.statusBreakdown.maintenance || 0}%`],
        ],
        styles: { fontSize: 9, cellPadding: 3 },
        headStyles: { fillColor: [0, 31, 63] },
        alternateRowStyles: { fillColor: [245, 245, 245] },
      });

      yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
    }
  }

  // Device details from backend
  if (reportData.devices) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Device Details', 20, yPos);
    yPos += 7;

    const deviceData = reportData.devices.map((device: any) => [
      device.deviceId,
      device.name || 'N/A',
      device.type || 'N/A',
      device.status?.toUpperCase() || 'UNKNOWN',
      device.firmwareVersion || 'N/A',
      device.lastSeen ? dayjs(device.lastSeen).format('MMM D, YYYY HH:mm') : 'N/A',
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [['Device ID', 'Name', 'Type', 'Status', 'Firmware', 'Last Seen']],
      body: deviceData,
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [0, 31, 63] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      columnStyles: {
        3: { fontStyle: 'bold' }
      },
      didParseCell: function(data: any) {
        if (data.column.index === 3) {
          const status = data.cell.raw.toLowerCase();
          if (status === 'online') {
            data.cell.styles.textColor = [82, 196, 26];
          } else if (status === 'offline') {
            data.cell.styles.textColor = [128, 128, 128];
          } else {
            data.cell.styles.textColor = [255, 77, 79];
          }
        }
      },
    });
  }

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text(
      `IoT Device Management System - ${dayjs().format('YYYY')}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
};
