import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig } from '../../../../schemas';

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

export const generateWaterQualityReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF();
  let yPos = 20;

  // ============================================================================
  // HEADER SECTION
  // ============================================================================
  doc.setFillColor(0, 31, 63); // Navy blue
  doc.rect(0, 0, 210, 45, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text('Water Quality Analysis Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(config.title || 'Comprehensive Water Quality Assessment', 105, 30, { align: 'center' });
  
  // Report ID
  const reportId = `WQR-${dayjs().format('YYYYMMDD')}-${Math.random().toString(36).substr(2, 6).toUpperCase()}`;
  doc.setFontSize(9);
  doc.text(`Report ID: ${reportId}`, 105, 38, { align: 'center' });

  // Reset text color
  doc.setTextColor(0, 0, 0);
  yPos = 55;

  // ============================================================================
  // REPORT INFORMATION SECTION
  // ============================================================================
  doc.setFillColor(245, 245, 245);
  doc.rect(15, yPos - 3, 180, 35, 'F');
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 31, 63);
  doc.text('Report Information', 20, yPos + 3);
  doc.setTextColor(0, 0, 0);
  yPos += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`, 20, yPos);
  doc.text(`Generated By: ${config.generatedBy || 'System Administrator'}`, 110, yPos);
  yPos += 5;
  
  if (reportData.period) {
    doc.text(
      `Report Period: ${dayjs(reportData.period.start).format('MMM D, YYYY')} - ${dayjs(reportData.period.end).format('MMM D, YYYY')}`,
      20,
      yPos
    );
    yPos += 5;
  }
  
  doc.text(`Devices Monitored: ${reportData.devices?.length || config.deviceIds.length}`, 20, yPos);
  doc.text(`Total Readings: ${reportData.summary?.totalReadings || 0}`, 110, yPos);
  yPos += 5;
  
  if (config.notes) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.text(`Notes: ${config.notes}`, 20, yPos);
    doc.setFont('helvetica', 'normal');
    yPos += 5;
  }
  
  yPos += 5;

  // ============================================================================
  // EXECUTIVE SUMMARY
  // ============================================================================
  if (reportData.summary) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 31, 63);
    doc.text('Executive Summary', 20, yPos);
    doc.setTextColor(0, 0, 0);
    yPos += 8;

    const summary = reportData.summary;
    const overallStatus = getOverallStatus(summary);

    // Summary box
    doc.setFillColor(overallStatus.color[0], overallStatus.color[1], overallStatus.color[2]);
    doc.rect(20, yPos - 3, 170, 30, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`Overall Water Quality: ${overallStatus.status}`, 25, yPos + 3);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    yPos += 10;

    // Check if we have actual data (not just zeros)
    const hasData = summary.averageTurbidity !== undefined && 
                    summary.totalReadings > 0;

    if (hasData) {
      doc.text(`Average Turbidity: ${summary.averageTurbidity.toFixed(2)} NTU (Safe: <= 5 NTU)`, 25, yPos);
      yPos += 5;
      doc.text(`Average TDS: ${summary.averageTDS.toFixed(2)} ppm (Safe: <= 500 ppm)`, 25, yPos);
      yPos += 5;
      doc.text(`Average pH: ${summary.averagePH.toFixed(2)} (Safe: 6.5 - 8.5)`, 25, yPos);
      yPos += 5;
    } else {
      doc.text('No sensor data available for the selected period', 25, yPos);
      yPos += 5;
      doc.text('Please check device connectivity and try a different date range', 25, yPos);
      yPos += 5;
    }

    doc.setTextColor(0, 0, 0);
    yPos += 8;
  }

  // Process devices from backend data
  if (reportData.devices && reportData.devices.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Device Analysis', 20, yPos);
    yPos += 7;

    for (const deviceReport of reportData.devices) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(`Device: ${deviceReport.deviceName || deviceReport.deviceId}`, 20, yPos);
      yPos += 5;

      if (deviceReport.location) {
        doc.setFont('helvetica', 'normal');
        doc.text(`Location: ${deviceReport.location}`, 20, yPos);
        yPos += 5;
      }

      // Metrics from backend
      if (deviceReport.metrics) {
        const metrics = deviceReport.metrics;
        
        autoTable(doc, {
          startY: yPos,
          head: [['Parameter', 'Average', 'Min/Max', 'Safe Range', 'Status']],
          body: [
            [
              'Turbidity',
              `${metrics.avgTurbidity?.toFixed(2) || 'N/A'} NTU`,
              `${metrics.minTurbidity?.toFixed(2) || 'N/A'} / ${metrics.maxTurbidity?.toFixed(2) || 'N/A'}`,
              '0 - 5 NTU',
              (metrics.avgTurbidity || 0) <= 5 ? 'GOOD' : 'WARNING'
            ],
            [
              'TDS',
              `${metrics.avgTDS?.toFixed(2) || 'N/A'} ppm`,
              `${metrics.minTDS?.toFixed(2) || 'N/A'} / ${metrics.maxTDS?.toFixed(2) || 'N/A'}`,
              '0 - 500 ppm',
              (metrics.avgTDS || 0) <= 500 ? 'GOOD' : 'WARNING'
            ],
            [
              'pH Level',
              metrics.avgPH?.toFixed(2) || 'N/A',
              `${metrics.minPH?.toFixed(2) || 'N/A'} / ${metrics.maxPH?.toFixed(2) || 'N/A'}`,
              '6.5 - 8.5',
              ((metrics.avgPH || 0) >= 6.5 && (metrics.avgPH || 0) <= 8.5) ? 'GOOD' : 'WARNING'
            ],
          ],
          styles: { fontSize: 7, cellPadding: 2 },
          headStyles: { fillColor: [0, 31, 63], textColor: [255, 255, 255] },
          alternateRowStyles: { fillColor: [245, 245, 245] },
          columnStyles: {
            4: { 
              cellWidth: 20,
              fontStyle: 'bold',
            }
          },
          didParseCell: function(data: any) {
            if (data.column.index === 4) {
              const status = data.cell.raw;
              if (status === 'GOOD') {
                data.cell.styles.textColor = [82, 196, 26];
              } else {
                data.cell.styles.textColor = [250, 173, 20];
              }
            }
          },
        });

        yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
      }

      // Alerts from backend
      if (deviceReport.alerts && deviceReport.alerts.length > 0) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Alerts:', 20, yPos);
        yPos += 5;

        deviceReport.alerts.forEach((alert: any) => {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          const alertColor: [number, number, number] = alert.severity === 'high' ? [255, 77, 79] : [250, 173, 20];
          doc.setTextColor(...alertColor);
          doc.text(`• ${alert.message}`, 25, yPos);
          doc.setTextColor(0, 0, 0);
          yPos += 4;
        });
        yPos += 5;
      }
    }
  }

  // ============================================================================
  // RECOMMENDATIONS SECTION (if issues found)
  // ============================================================================
  const hasIssues = reportData.devices?.some((d: any) => d.alerts && d.alerts.length > 0);
  if (hasIssues) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 31, 63);
    doc.text('Recommendations & Action Items', 20, yPos);
    doc.setTextColor(0, 0, 0);
    yPos += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    
    const recommendations = generateRecommendations(reportData);
    recommendations.forEach((rec, index) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(`${index + 1}. ${rec}`, 20, yPos, { maxWidth: 170 });
      yPos += 7;
    });
  }

  // ============================================================================
  // FOOTER
  // ============================================================================
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text(
      `Generated by IoT Water Quality Monitoring System - ${dayjs().format('YYYY')} | Report ID: ${reportId}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Determine overall water quality status based on summary metrics
 */
function getOverallStatus(summary: any): { status: string; color: [number, number, number] } {
  // Check if summary exists and has numeric values (use !== undefined to handle 0 values)
  if (!summary || 
      (summary.averageTurbidity === undefined && 
       summary.averageTDS === undefined && 
       summary.averagePH === undefined)) {
    return { status: 'NO DATA', color: [128, 128, 128] };
  }

  // If values are all 0, that's also no data
  if (summary.averageTurbidity === 0 && 
      summary.averageTDS === 0 && 
      summary.averagePH === 0 &&
      summary.totalReadings === 0) {
    return { status: 'NO DATA', color: [128, 128, 128] };
  }

  const turbidityOk = (summary.averageTurbidity || 0) <= 5;
  const tdsOk = (summary.averageTDS || 0) <= 500;
  const phOk = (summary.averagePH || 0) >= 6.5 && (summary.averagePH || 0) <= 8.5;

  const okCount = [turbidityOk, tdsOk, phOk].filter(Boolean).length;

  if (okCount === 3) {
    return { status: 'EXCELLENT', color: [82, 196, 26] }; // Green
  } else if (okCount === 2) {
    return { status: 'GOOD', color: [82, 196, 26] }; // Green
  } else if (okCount === 1) {
    return { status: 'FAIR - ATTENTION NEEDED', color: [250, 173, 20] }; // Orange
  } else {
    return { status: 'POOR - IMMEDIATE ACTION REQUIRED', color: [255, 77, 79] }; // Red
  }
}

/**
 * Generate recommendations based on report data
 */
function generateRecommendations(reportData: any): string[] {
  const recommendations: string[] = [];
  
  if (!reportData.devices || reportData.devices.length === 0) {
    return ['No devices found. Please check device configuration and connectivity.'];
  }

  const summary = reportData.summary;
  
  // Check for high turbidity
  if (summary?.averageTurbidity && summary.averageTurbidity > 5) {
    recommendations.push(
      `High turbidity detected (${summary.averageTurbidity.toFixed(2)} NTU). ` +
      'Investigate potential contamination sources and consider filtration system maintenance.'
    );
  }

  // Check for high TDS
  if (summary?.averageTDS && summary.averageTDS > 500) {
    recommendations.push(
      `Elevated TDS levels detected (${summary.averageTDS.toFixed(2)} ppm). ` +
      'Consider water treatment to reduce dissolved solids. Schedule pipe system inspection.'
    );
  }

  // Check for pH issues
  if (summary?.averagePH) {
    if (summary.averagePH < 6.5) {
      recommendations.push(
        `Low pH detected (${summary.averagePH.toFixed(2)}). Water is acidic. ` +
        'Install pH adjustment system. Check for corrosion in pipes.'
      );
    } else if (summary.averagePH > 8.5) {
      recommendations.push(
        `High pH detected (${summary.averagePH.toFixed(2)}). Water is alkaline. ` +
        'Install pH adjustment system. Test for mineral buildup.'
      );
    }
  }

  // Check for devices with no data
  const devicesWithNoData = reportData.devices.filter((d: any) => 
    !d.metrics || d.metrics.totalReadings === 0
  );
  if (devicesWithNoData.length > 0) {
    recommendations.push(
      `${devicesWithNoData.length} device(s) reported no data during this period. ` +
      'Check device connectivity, power supply, and sensor calibration.'
    );
  }

  // General maintenance
  if (recommendations.length === 0) {
    recommendations.push(
      'All parameters are within safe ranges. Continue regular monitoring and maintenance schedule.',
      'Perform sensor calibration as per manufacturer guidelines (typically every 3-6 months).',
      'Review historical trends to identify any gradual changes in water quality.'
    );
  } else {
    recommendations.push(
      'Schedule immediate inspection of flagged devices and water quality parameters.',
      'Increase monitoring frequency until issues are resolved.',
      'Document all corrective actions taken and verify effectiveness.'
    );
  }

  return recommendations;
}
