import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';
import type { ReportConfig } from '../../../../schemas';

// Type extension for jsPDF with autoTable plugin
interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable?: {
    finalY: number;
  };
}

export const generateWaterQualityReport = async (
  config: ReportConfig,
  reportData: any
): Promise<jsPDF> => {
  const doc = new jsPDF();
  let yPos = 20;

  // Add header with logo placeholder
  doc.setFillColor(0, 31, 63); // Navy blue
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Water Quality Analysis Report', 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(config.title, 105, 30, { align: 'center' });

  // Reset text color
  doc.setTextColor(0, 0, 0);
  yPos = 50;

  // Report Information from backend data
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Information', 20, yPos);
  yPos += 7;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Generated: ${dayjs().format('MMMM D, YYYY [at] h:mm A')}`, 20, yPos);
  yPos += 5;
  doc.text(`Generated By: ${config.generatedBy}`, 20, yPos);
  yPos += 5;
  
  if (reportData.period) {
    doc.text(
      `Period: ${dayjs(reportData.period.start).format('MMM D, YYYY')} - ${dayjs(reportData.period.end).format('MMM D, YYYY')}`,
      20,
      yPos
    );
    yPos += 5;
  }
  
  doc.text(`Devices Monitored: ${reportData.devices?.length || config.deviceIds.length}`, 20, yPos);
  yPos += 10;

  // Process devices from backend data
  if (reportData.devices && reportData.devices.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Device Analysis', 20, yPos);
    yPos += 7;

    for (const deviceReport of reportData.devices) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(`Device: ${deviceReport.deviceName || deviceReport.deviceId}`, 20, yPos);
      yPos += 5;

      if (deviceReport.location) {
        doc.setFont('helvetica', 'normal');
        doc.text(`Location: ${deviceReport.location}`, 20, yPos);
        yPos += 5;
      }

      // Metrics from backend
      if (deviceReport.metrics) {
        const metrics = deviceReport.metrics;
        
        autoTable(doc, {
          startY: yPos,
          head: [['Parameter', 'Average', 'Min/Max', 'Safe Range', 'Status']],
          body: [
            [
              'Turbidity',
              `${metrics.avgTurbidity?.toFixed(2) || 'N/A'} NTU`,
              `${metrics.minTurbidity?.toFixed(2) || 'N/A'} / ${metrics.maxTurbidity?.toFixed(2) || 'N/A'}`,
              '0 - 5 NTU',
              (metrics.avgTurbidity || 0) <= 5 ? 'GOOD' : 'WARNING'
            ],
            [
              'TDS',
              `${metrics.avgTDS?.toFixed(2) || 'N/A'} ppm`,
              `${metrics.minTDS?.toFixed(2) || 'N/A'} / ${metrics.maxTDS?.toFixed(2) || 'N/A'}`,
              '0 - 500 ppm',
              (metrics.avgTDS || 0) <= 500 ? 'GOOD' : 'WARNING'
            ],
            [
              'pH Level',
              metrics.avgPH?.toFixed(2) || 'N/A',
              `${metrics.minPH?.toFixed(2) || 'N/A'} / ${metrics.maxPH?.toFixed(2) || 'N/A'}`,
              '6.5 - 8.5',
              ((metrics.avgPH || 0) >= 6.5 && (metrics.avgPH || 0) <= 8.5) ? 'GOOD' : 'WARNING'
            ],
          ],
          styles: { fontSize: 7, cellPadding: 2 },
          headStyles: { fillColor: [0, 31, 63], textColor: [255, 255, 255] },
          alternateRowStyles: { fillColor: [245, 245, 245] },
          columnStyles: {
            4: { 
              cellWidth: 20,
              fontStyle: 'bold',
            }
          },
          didParseCell: function(data: any) {
            if (data.column.index === 4) {
              const status = data.cell.raw;
              if (status === 'GOOD') {
                data.cell.styles.textColor = [82, 196, 26];
              } else {
                data.cell.styles.textColor = [250, 173, 20];
              }
            }
          },
        });

        yPos = (doc as jsPDFWithAutoTable).lastAutoTable?.finalY ?? yPos + 10;
      }

      // Alerts from backend
      if (deviceReport.alerts && deviceReport.alerts.length > 0) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Alerts:', 20, yPos);
        yPos += 5;

        deviceReport.alerts.forEach((alert: any) => {
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          const alertColor: [number, number, number] = alert.severity === 'high' ? [255, 77, 79] : [250, 173, 20];
          doc.setTextColor(...alertColor);
          doc.text(`• ${alert.message}`, 25, yPos);
          doc.setTextColor(0, 0, 0);
          yPos += 4;
        });
        yPos += 5;
      }
    }
  }

  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text(
      `Generated by IoT Water Quality Monitoring System - ${dayjs().format('YYYY')}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
};
